### ISSUE TITLE
As a growing person, I want to edit or delete my habits so I can keep my habits up to date.

### ISSUE THREAD

**Issue by maalolan210** [cse442-at-ub/project_s23-atomic#13]
**Acceptance Tests**

*Test 1 - Title & Details*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/ and click the Sign Up button
2. Register with (or login if username/email already exists):
    wEdit1
    wEdit1@example.com
    wEdit123
    wEdit123
and then click the Continue button
3. On the page "You're One Step Closer", Select 3 habits preset habits when prompted, choosing "Journal", "Drink Alcohol", and "Drink Coffee", then click next
4. Find the "Journal" habit on the homepage. Click the + button below to increment **once**.
5. Click the Title "Journal" and verify you are taken to a new page displaying the habit details
6. Click the Edit button and verify you are taken to a new page titled "Edit Habit"
7. Change the title to "Write down one good day event"
8. Change the details to "Remember the good times!"
9. Click the Submit button and verify you are returned to the page displaying the habit in detail
10. Verify the habit details display with the updated Title and Details, and with **the same counter "1/1"**

*Test 2 - Labels and Counter*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/
2. Register with (or login if username/email already exists):
    wEdit1
    wEdit1@example.com
    wEdit123
    wEdit123
and then click the Continue button
3. On the page "You're One Step Closer", Select 3 habits preset habits when prompted, choosing "Journal", "Drink Alcohol", and "Drink Coffee", then click next
4. Find the "Drink Coffee" habit on the homepage. Click the + button twice below to increment twice
5. Click the Title "Drink Coffee" and verify you are taken to a new page displaying the habit details
6. Click the Edit button and verify you are taken to a new page titled "Edit Habit"
7. Using the dropdown, change the category to "Social"
8. Using the dropdown, change the type to "Good"
9. Change the "Daily Goal Counter" to 1
10. Click the Submit button and verify you are returned to the page displaying the habit in detail
11. Verify the habit details display the updated Category and Type tags, and with a counter of "2/1", with the same Title and Details

*Test 3- Delete*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/
2. Register with (or login if username/email already exists):
    wEdit1
    wEdit1@example.com
    wEdit123
    wEdit123
and then click the Continue button
3. On the page "You're One Step Closer", Select 3 habits preset habits when prompted, choosing "Journal", "Drink Alcohol", and "Drink Coffee", then click next
4. Find the "Drink Alcohol" habit on the homepage. Click the + button twice to increment twice.
5. Click the Title "Drink Alcohol" and verify you are taken to a new page displaying the habit details
6. Click the Delete button
7. Verify you are returned to the home page and "Drink Alcohol" does not show up on the page

**Comment by susanbrethauer** [comment]
This user story seems nearly the same as #12
