### ISSUE TITLE
Create Backend Login

### ISSUE THREAD

**Issue by FardinApurbo** [cse442-at-ub/project_s23-atomic#22]
This task is to create the backend for the login system, this will not be connected to a front end yet. Fetching the user data from the database to confirm its match is the main goal here.

Test-1
Testing for valid credentials:

1. open the connection.php file and then change the name of the database to your local machines database.
2. open your browser and go to localhost/login/login.php
3. click on signup at the bottom of the login box
4. enter your name and a password to create an account
5. Log in using the username and password that you used to signup
6. If it matches the credentials then it should take you to the index page

Test-2
Test invalid username:

1. open the connection.php file and then change the name of the database to your local machines database.
2. open your browser and go to localhost/login/login.php
3. click on signup at the bottom of the login box
4. sign up with a valid username and password
5. then log in but don't use the same username you used to sign up
6. it should give out an error message

Test-3
Test invalid password:

1. open the connection.php file and then change the name of the database to your local machines database.
2. open your browser and go to localhost/login/login.php
3. click on signup at the bottom of the login box
4. sign up with a valid username and password
5. then log in but don't use the same password you used to sign up
6. it should give out an error message

Test-4
Test empty fields:

1. open the connection.php file and then change the name of the database to your local machines database.
2. open your browser and go to localhost/login/login.php
3. it will take you to the login page
4. keep it blank and hit login button
5. it should prompt you to enter valid credentials

**Comment by susanbrethauer** [comment]
tests need to be written for this task and it needs to be tested and work with a dummy log in.
