### ISSUE TITLE
Create Data Visuals for Habits

### ISSUE THREAD

**Issue by karli-T** [cse442-at-ub/project_s23-atomic#39]
**Task Tests**
*Test 1*
1. Go to [https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/] and verify there are Sign Up and log in buttons
2. Click Log In and verify you are redirected to the log in page
3. Enter the credentials: username [kween], and password [password1234] and click Log In
4. Verify you are taken to the home page with habits displayed on the page in their correct categories
5. Under any habits of your choice, click the plus button to increment the log number up to the total number
6. On the top navbar, click the statistics link on the right side and verify you are taken to a statistics page with a bar graph titled "Daily Progress" with all the habits listed on the x-axis
7. Click the drop down menu on the right and choose the Bad Habits to filter the graph to show data for bad habit tracking
8. Verify the graph changes only displaying bad habits

*Test 2*
1. Go to [https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/] and verify there are Sign Up and log in buttons
2. Click Log In and verify you are redirected to the log in page
3. Enter the credentials: username [kween], and password [password1234] and click Log In
4. Verify you are taken to the home page with habits displayed on the page in their correct categories
5. Under any habits of your choice, click the plus button to increment the log number up to the total number
6. On the top navbar, click the statistics link on the right side and verify you are taken to a statistics page with a bar graph titled "Daily Progress" with all the habits listed on the x-axis
7. Click the drop down menu and choose the Bad Habits to filter the graph to show data for bad habit tracking
8. Verify the graph changes only displaying bad habits
9. In the second drop down menu, choose a specific habit to filter by, like smoke, and verify the graph changes to a line graph showing the weekly statistics for Smoking

*Test 3*
1. Go to [https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/] and verify there are Sign Up and log in buttons
2. Click Log In and verify you are redirected to the log in page
3. Enter the credentials: username [kween], and password [password1234] and click Log In
4. Verify you are taken to the home page with habits displayed on the page in their correct categories
5. Under any habits of your choice, click the plus button to increment the log number up to the total number
6. On the top navbar, click the statistics link on the right side and verify you are taken to a statistics page with a bar graph titled "Daily Progress" with all the habits listed on the x-axis
7. Click the drop down menu and choose the Good Habits to filter the graph to show data for good habit tracking
8. Verify the graph changes only displaying good habits

*Test 4*
1. Go to [https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/] and verify there are Sign Up and log in buttons
2. Click Log In and verify you are redirected to the log in page
3. Enter the credentials: username [kween], and password [password1234] and click Log In
4. Verify you are taken to the home page with habits displayed on the page in their correct categories
5. Under any habits of your choice, click the plus button to increment the log number up to the total number
6. On the top navbar, click the statistics link on the right side and verify you are taken to a statistics page with a bar graph titled "Daily Progress" with all the habits listed on the x-axis
7. Click the drop down menu and choose the Good Habits to filter the graph to show data for Good habit tracking
8. Verify the graph changes only displaying bad habits
9. In the second drop down menu, choose a specific habit to filter by, like drink water, and verify the graph changes to a line graph showing the weekly statistics for Drinking Water

**Comment by susanbrethauer** [comment]
tests look good just make sure to update the links and login info. Putting label on so it doesn't get lost in the end of sprint rush
