### ISSUE TITLE
As a person looking to start new habits, I want to be able to create an account with unique credentials to be able to use the application and log my daily habits.

### ISSUE THREAD

**Issue by maalolan210** [cse442-at-ub/project_s23-atomic#7]
**Acceptance Tests**
*Test 1*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/
2. Verify you are taken to the landing page
3. Click the "Sign Up" button and verify you are taken to a new sign-up page
4. Verify there are four input boxes to fill in your information (username, email, password, and confirm password)
5. Fill in the input boxes with the credentials: Username [icant], Email [ican@gmail.com], Password [12345678], Confirm Password [12345678]
6. Click the "Continue" button and verify you are redirected to a new page that says "Choose your Habits"
7. Choose three habits (Meditate, Exercise, and Eat Junk Food) and verify you can click the checkboxes (they should turn blue)
8. Click the "Next" button and verify you are taken to the home page

*Test 2*
1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/
2. Verify you are taken to the landing page
3. Click the "Log in" button and verify you are taken to a log-in page
4. Verify there are two input boxes to fill in your information (username and password)

**Comment by susanbrethauer** [comment]
There is a disconnect between the person and the action of this user story. Why do only college students want to create accounts? Why do they want to create accounts?

**Comment by susanbrethauer** [comment]
for test 1, step seven make the habits that they should click more specific, which boxes do they need to press.
