### ISSUE TITLE
As a college student/athlete/business person, I want to view my habit statistics so I can visually see what areas of my life need improvement or have been improving.

### ISSUE THREAD

**Issue by maalolan210** [cse442-at-ub/project_s23-atomic#8]
**Acceptance Tests**
*Test 1*
1. Go to [https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/] and verify there are Sign Up and log in buttons
2. Click Log In and verify you are redirected to the log in page
3. Enter the credentials: username [kween], and password [password1234] and click Log In
4. Verify you are taken to the home page with habits displayed on the page in their correct categories
5. Click the plus button under the habits, Drink Water, Smoke, and Clean, and verify the log numbers increment up by 1
6. On the top navbar, click the statistics link in the middle and verify you are taken to a statistics page with a bar graph titled "Daily Progress" with all the habits listed on the x-axis
7. Click the drop down menu on the right where it says "All" and choose the Good Habits option to filter the graph to only show data for good habits
8. Verify the bar graph changes only displaying good habits with Drink Water and Clean having a bar up to 1

*Test 2*
1. Go to [https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/] and verify there are Sign Up and log in buttons
2. Click Log In and verify you are redirected to the log in page
3. Enter the credentials: username [kween], and password [password1234] and click Log In
4. Verify you are taken to the home page with habits displayed on the page in their correct categories
5. Click the plus button under the habits, Smoke, Clean, Drink Water, and verify the log number increment by 1
6. On the top navbar, click the statistics link in the middle and verify you are taken to a statistics page with a bar graph titled "Daily Progress" with all the habits listed on the x-axis
7. Click the drop down menu on the right where it says "All" and choose the Bad Habits option to filter the graph to only show data for bad habit tracking
8. Verify the bar graph changes only displaying bad habits with Smoke having a bar up to 1

*Test 3*
1. Go to [https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/] and verify there are Sign Up and log in buttons
2. Click Log In and verify you are redirected to the log in page
3. Enter the credentials: username [kween], and password [password1234] and click Log In
4. Verify you are taken to the home page with habits displayed on the page in their correct categories
5. On the top navbar, click the statistics link in the middle and verify you are taken to a statistics page with a bar graph titled "Daily Progress" with all the habits listed on the x-axis
6. Click the drop down menu on the right where it says "All" and choose the Bad Habits option to filter the graph to show data for bad habit tracking
7. Verify the graph changes only displaying bad habits
8. In the second drop down menu below, choose a specific habit to filter by, like smoke, and verify the graph changes to a line graph showing the weekly statistics for Smoking and the title changes to "Weekly Progress for Smoke"

*Test 4*
1. Go to [https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442q/] and verify there are Sign Up and log in buttons
2. Click Log In and verify you are redirected to the log in page
3. Enter the credentials: username [kween], and password [password1234] and click Log In
4. Verify you are taken to the home page with habits displayed on the page in their correct categories
5. On the top navbar, click the statistics link in the middle and verify you are taken to a statistics page with a bar graph titled "Daily Progress" with all the habits listed on the x-axis
6. Click the drop down menu below and choose the Good Habits option to filter the graph to show data for good habit tracking
7. Verify the graph changes only displaying good habits
8. In the second drop down menu, choose a specific habit to filter by, like Drink Water, and verify the graph changes to a line graph showing the weekly statistics for Drinking Water and the title changes to "Weekly Progress for Drink Water"

**Comment by susanbrethauer** [comment]
make sure to change all the links and usernames/passwords before the end of sprint
